create DATABASE `CANDIDATODB` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci;

create TABLE IF NOT EXISTS CANDIDATO (
    CANDIDATO_ID INT NOT NULL AUTO_INCREMENT,
    NOMBRE_APPELIDO VARCHAR(60) NOT NULL,
    DNI VARCHAR(20) NOT NULL,
    FECHA_NACIMIENTO DATE  NOT NULL,
    DOMICILIO VARCHAR(35)  NOT NULL,
    TELEFONO VARCHAR(20)  NOT NULL,
    EMAIL VARCHAR(30)  NOT NULL,
    PRIMARY KEY (CANDIDATO_ID)
);


create TABLE IF NOT EXISTS USUARIO (
    USUARIO_ID INT NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(60) NOT NULL,
    PASSWORD VARCHAR(20) NOT NULL,
    PRIMARY KEY (USUARIO_ID)
);


create TABLE IF NOT EXISTS ROL (
    ROL_ID INT NOT NULL AUTO_INCREMENT,
    ROL VARCHAR(60) NOT NULL,
    USUARIO INT NOT NULL,
    PRIMARY KEY (ROL_ID),
    FOREIGN KEY(USUARIO) REFERENCES USUARIO(USUARIO_ID)
);