CREATE DATABASE `CANDIDATODB` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci;

CREATE TABLE IF NOT EXISTS CANDIDATO (
    CANDIDATO_ID INT NOT NULL AUTO_INCREMENT,
    NOMBRE_APPELIDO VARCHAR(60) NOT NULL,
    DNI VARCHAR(20) NOT NULL,
    FECHA_NACIMIENTO DATE  NOT NULL,
    DOMICILIO VARCHAR(35)  NOT NULL,
    TELEFONO VARCHAR(20)  NOT NULL,
    EMAIL VARCHAR(30)  NOT NULL,
    PRIMARY KEY (CANDIDATO_ID)
);